using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PayValueManualSln.Application.DTOs.Assesment
{
    public class AssessmentDTO
    {
        //public long AssessmentId { get; set; }
        //public string AssessmentRefNo { get; set; }
        //public string MerchantCode { get; set; }
        //public string Location { get; set; }
        //public string PayerName { get; set; }
        //public string Telephone { get; set; }
        //public string Address { get; set; }
        //public decimal? TotalAmount { get; set; }
        //public string Narration { get; set; }
        //public string RevenueCode { get; set; }
        //public string RevenueName { get; set; }
        //public string AgencyCode { get; set; }
        //public string AgencyName { get; set; }
        //public string Platformcode { get; set; }
        //public decimal? AmountPaid { get; set; }
        //public decimal? AssessmentBalance { get; set; }
        //public bool? PartPaymentAllow { get; set; }
        //public long? ParentId { get; set; }
        //public DateTime? DateCreated { get; set; }
        //public bool? IsReversed { get; set; }
        //public string Reversedby { get; set; }
        //public DateTime? DateReversed { get; set; }
        //public string AgentUtin { get; set; }
        //public string TaxYear { get; set; }
        //public string PreviousYearAssessmentRefNo { get; set; }
        //public string AssessmentCreatedBy { get; set; }
        //public DateTime? AssessmentCreatedDate { get; set; }
        //public string AssessmentApprovedBy { get; set; }
        //public DateTime? AssessmentDateApproved { get; set; }
        //public bool? PushtoXpress { get; set; }
        //public DateTime? DatePushtoXpress { get; set; }

        public long? ServiceId { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public string PaymentDays { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? DateCreated { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DateUpdated { get; set; }
        public int? Approval { get; set; }
        public string Approvedby { get; set; }
        public DateTime? DateApproved { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsRebated { get; set; }
        public string AgencyCode { get; set; }
        public long? DeptId { get; set; }
        public long? BPMSServiceId { get; set; }

        public long Id { get; set; }
        public string RequestId { get; set; }
        public string ServiceType { get; set; }
        public string MerchantNo { get; set; }
        public string PayerRefNo { get; set; }
        public string Name { get; set; }
        public string PayerName { get; set; }
        public string Address { get; set; }
        public string AgencyAddress { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public long? RateId { get; set; }
        public long? CategoryId { get; set; }
        public long? SubcategoryId { get; set; }
        public long? SubSubcategoryId { get; set; }
        public string PaymentItem { get; set; }
        public string BaseAssnumber { get; set; }
        public string AssessementRefNo { get; set; }
        public string AssessementPeriod { get; set; }
        public decimal? AssesementAmount { get; set; }
        public string AssesementAmountFormatted { get; set; }
        public string RebateAmountFormatted { get; set; }
        public decimal? RebateAmount { get; set; }
        public decimal? RebatePercentage { get; set; }
        public decimal? AssesementAmountpaid { get; set; }
        public decimal? AssessmentBalance { get; set; }
        public string AssessmentBalanceFormatted { get; set; }
        public string Descriptions { get; set; }
        public string RevenueCode { get; set; }
        public string RevenueName { get; set; }
        public string Platformcode { get; set; }
        public bool? PartPaymentAllow { get; set; }
        public long? ParentID { get; set; }
        public string PaymentRefNo { get; set; }
        public string Status { get; set; }
        public string PaymentStatus { get; set; }
        public string TotalAmountFormatted { get; set; }
        public decimal? TotalAmount => AssesementAmount + RebateAmount;
        public string SRC { get; set; }
        public string StateGovernorName { get; set; }
        public string ServiceHeader { get; set; }
        public string ServiceSubHeader { get; set; }
        public bool? IsReversed { get; set; }
        public DateTime? LastPaymentDate { get; set; }
        public DateTime DateSubmitted { get; set; }
        public string Addedby { get; set; }
        public string Updatedby { get; set; }
        public bool? IsRevised { get; set; }
        public string ReviseInitiatedby { get; set; }
        public DateTime? DateRevised { get; set; }
        public string StandardLetterDescriptions { get; set; }
        public string UsedCategoryName { get; set; }
        public string CategoryName => AssessmentCategoryName == null ? UsedCategoryName : AssessmentCategoryName;
        public string AssessmentCategoryName { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovalComments { get; set; }
        public string Description1 { get; set; }
        public string Size { get; set; }
        public string Location1 { get; set; }
        public string Others { get; set; }
        public string ReviseApprovedby { get; set; }
        public DateTime? DateReviseApproved { get; set; }
        public bool? isdeleted { get; set; }
        public string DeletedBy { get; set; }
        public DateTime? DateDeleted { get; set; }
        public string ReasonforDeletion { get; set; }
        public bool? UpdateRepository { get; set; }
        public DateTime? DateUpdateRepository { get; set; }
        public int? StatusId { get; set; }
        public int? State { get; set; }
        public int? LGA { get; set; }
        public int? City { get; set; }
        public bool? SRCUpdated { get; set; }
        public DateTime? SRCDateUpdated { get; set; }
        public bool? RebateAllowed { get; set; }
        public DateTime? DateRebateApproved { get; set; }
        public string AddedByUserName { get; set; }
        public string TransactionYear { get; set; }
        public bool? UpdateBPMS { get; set; }
        public DateTime? DateUpdateBPMS { get; set; }
        public string PaymentCode { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
        public int? MaxApproval { get; set; }
        public int? ApprovalCount { get; set; }
        public string Value { get; set; }
        public string Page { get; set; }
        public string Size1 { get; set; }
        public string Size2 { get; set; }
        public string DocumentAmount { get; set; }
        public int? IsFailed { get; set; }
        public string SignatoryName { get; set; }
        public string SignatoryPosition { get; set; }
        public string RentRevisionPeriod { get; set; }
        public string AgencyPhone { get; set; }
        public string AgencyName { get; set; }
        public string AgencyEmail { get; set; }
        public string AgencyAddress1 { get; set; }
        public string AgencyAddress2 { get; set; }
        public string AgencyLogo { get; set; }
        public string AgencySignature { get; set; }
        public bool? IsMailSent { get; set; }
        public bool? ShowRebatePercentage { get; set; }
        public Guid BillInfoGuid { get; set; }
        public List<BillDetailsDto> BillDetails { get; set; }
    }

    public class AssessmentsDto
    {
        public long? ServiceId { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public string PaymentDays { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? DateCreated { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DateUpdated { get; set; }
        public int? Approval { get; set; }
        public string Approvedby { get; set; }
        public DateTime? DateApproved { get; set; }
        public bool? IsDeleted { get; set; }
        public string AgencyCode { get; set; }
        public long? DeptId { get; set; }
        public long? BPMSServiceId { get; set; }
        public long Id { get; set; }
        public string RequestId { get; set; }
        public string MerchantNo { get; set; }
        public string PayerRefNo { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public long? RateId { get; set; }
        public long? CategoryId { get; set; }
        public long? SubcategoryId { get; set; }
        public long? SubSubcategoryId { get; set; }
        public string PaymentItem { get; set; }
        public string BaseAssnumber { get; set; }
        public string AssessementRefNo { get; set; }
        public string AssessementPeriod { get; set; }
        public decimal? AssesementAmount { get; set; }
        public string AssesementAmountFormatted { get; set; }
        public string RebateAmountFormatted { get; set; }
        public decimal? RebateAmount { get; set; }
        public decimal? RebatePercentage { get; set; }
        public decimal? AssesementAmountpaid { get; set; }
        public decimal? AssessmentBalance { get; set; }
        public string AssessmentBalanceFormatted { get; set; }
        public string Descriptions { get; set; }
        public string RevenueCode { get; set; }
        public string RevenueName { get; set; }
        public string Platformcode { get; set; }
        public bool? PartPaymentAllow { get; set; }
        public long? ParentID { get; set; }
        public string PaymentRefNo { get; set; }
        public string Status { get; set; }
        public string PaymentStatus { get; set; }
        public string TotalAmountFormatted { get; set; }
        public decimal? TotalAmount => AssesementAmount + RebateAmount;
        public string SRC { get; set; }
        public string StateGovernorName { get; set; }
        public string ServiceHeader { get; set; }
        public string ServiceSubHeader { get; set; }
        public bool? IsReversed { get; set; }
        public DateTime? LastPaymentDate { get; set; }
        public DateTime DateSubmitted { get; set; }
        public string Addedby { get; set; }
        public string Updatedby { get; set; }
        public bool? IsRevised { get; set; }
        public string ReviseInitiatedby { get; set; }
        public DateTime? DateRevised { get; set; }
        public string StandardLetterDescriptions { get; set; }
        public string UsedCategoryName { get; set; }
        public string CategoryName => AssessmentCategoryName == null ? UsedCategoryName : AssessmentCategoryName;
        public string AssessmentCategoryName { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovalComments { get; set; }
        public string Description1 { get; set; }
        public string Size { get; set; }
        public string Location1 { get; set; }
        public string Others { get; set; }
        public string ReviseApprovedby { get; set; }
        public DateTime? DateReviseApproved { get; set; }
        public bool? isdeleted { get; set; }
        public string DeletedBy { get; set; }
        public DateTime? DateDeleted { get; set; }
        public string ReasonforDeletion { get; set; }
        public bool? UpdateRepository { get; set; }
        public DateTime? DateUpdateRepository { get; set; }
        public int? StatusId { get; set; }
        public int? State { get; set; }
        public int? LGA { get; set; }
        public int? City { get; set; }
        public bool? SRCUpdated { get; set; }
        public DateTime? SRCDateUpdated { get; set; }
        public bool? RebateAllowed { get; set; }
        public DateTime? DateRebateApproved { get; set; }
        public string AddedByUserName { get; set; }
        public string TransactionYear { get; set; }
        public bool? UpdateBPMS { get; set; }
        public DateTime? DateUpdateBPMS { get; set; }
        public string PaymentCode { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
        public int? MaxApproval { get; set; }
        public int? ApprovalCount { get; set; }
        public string Value { get; set; }
        public string Page { get; set; }
        public string Size1 { get; set; }
        public string Size2 { get; set; }
        public string DocumentAmount { get; set; }
        public int? IsFailed { get; set; }
        public string SignatoryName { get; set; }
        public string SignatoryPosition { get; set; }
        public string RentRevisionPeriod { get; set; }
        public string AgencyPhone { get; set; }
        public string AgencyName { get; set; }
        public string AgencyEmail { get; set; }
        public string AgencyAddress1 { get; set; }
        public string AgencyAddress2 { get; set; }
        public string AgencyLogo { get; set; }
        public string AgencySignature { get; set; }
        public bool? IsMailSent { get; set; }
        public bool? ShowRebatePercentage { get; set; }
        public Guid BillInfoGuid { get; set; }
        //public List<BillDetails> BillDetails { get; set; }
    }
}
